### ISSUE TITLE
How to avoid cave being visible on surface?

### ISSUE THREAD

**Issue by HydrolienF** [kntrel/Underilla#6]
Sorry to bother you again, but I'm not sure to understand how to generate caves only under the surface of the custom world.
I'm using strategy RELATIVE.

I have tried to lower upper_limit so that it won't create cave on surface when surface is over the ocean.
I'm using depth: 6.
![Capture d’écran (997)](https://github.com/Jeshuakrc/Underilla/assets/71718798/a8c88a95-52b5-4eee-a912-9d08c14ac628)
![Capture d’écran (995)](https://github.com/Jeshuakrc/Underilla/assets/71718798/500b0bc1-a987-41d2-b657-ad5190ec9ba2)
![Capture d’écran (996)](https://github.com/Jeshuakrc/Underilla/assets/71718798/333d39bd-50b4-4da8-9023-d7118aeb7be9)

**Comment by Jeshuakrc** [comment]
Hey! Not a problem at all 😁
There's a distinction worth pointing out between **noodle caves** and **noise caves**.

**Noise caves** are the 1.17+ ones, the big open blobs underground, those are generated **before** the world surface, and are the ones you may limit in the configuration.

**Noodle caves** are pre-1.17, the old ones, corridors that connect the noise caves together. Those are "carved" after surface generation. At this time, there's no way to control whether or not these caves stick out to the surface, as that step is taken by the vanilla generator. The only control over noodle caves is disabling them altogether through `generate_noodle_caves: false` in config.yml. This will prevent noodle caves from sticking out to the surface, but will also remove them in the underground. You'll still have noise caves, but cave systems will be less connected.

You may try disabling noodle caves from config, and could be enabling caves in WorldPainter, if you own the source .world file; otherwise, this is just an unfortunate limitation at the time.

**Comment by HydrolienF** [comment]
Ok, thanks for the explanation, I will try to manage it from world painter
